name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  Clippy:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo clippy --release -- -A clippy::type_complexity

  Check:
    runs-on: ubuntu-latest
    needs: Clippy
    steps: 
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --release
      
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}
    needs: Check
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
