name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:

  Check_and_Clippy:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -A clippy::type_complexity
      
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}
    needs: Check_and_Clippy
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
