name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  Clippy:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo clippy

  Check:
    runs-on: ubuntu-latest
    needs: Clippy
    steps: 
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo check
      
  build:
    runs-on: ubuntu-latest
    needs: Check
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose 
