name: Build and Release

on:
  release:
    types: [published]
      
permissions:
  contents: write
  
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Executable
      run: cargo build --release

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          targets/release/ddf-rs${{ matrix.os == 'windows-latest' && '.exe' || '' }}
