name: Build and Release

on:
  release:
    types: [published]
      
permissions:
  contents: write
  
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
        - os: ubuntu-latest
          extension: ''
        - os: windows-latest
          extension: '.exe'
        
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build settings
      run: cargo +nighlty rustc --release --print cfg

    - name: Build Executable
      run: cargo build --release

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/ddf-rs${{ matrix.extension }}
